### PR TITLE
Split out GitHub Actions workflow for building docs to a separate workflow

### PR DESCRIPTION
**Pull request by jchodera**
This PR splits out the GitHub Actions workflow for building sphinx docs to a separate CI workflow YAML to fix the CI startup failure that was caused by merging #80

### CODE REVIEW

**Comment by jchodera** [comment]
@yuanqing-wang : It looks like we need to make sure that espaloma and its dependencies are installed to build the Sphinx docs, since we are using top-level package imports in espaloma Python source files:
```
Running Sphinx v2.4.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/github/workspace/docs/conf.py", line 22, in <module>
    from espaloma import mm, nn, data, graphs
ImportError: cannot import name 'mm' from 'espaloma' (unknown location)

make: *** [Makefile:20: html] Error 2
```
The alternative would be to move the imports into functions so it would be possible to import espaloma files to inspect them and build API docs _without_ the need to install espaloma and all its dependencies.

**Comment by jchodera** [comment]
Another alternative I can easily try: Integrate the docs build step into normal CI.

**Comment by jchodera** [comment]
@yuanqing-wang : Looks like you also need to add your sphinx `conf.py` file to `docs/`?
```
Sphinx build html
  sphinx-build -b html /github/workspace/docs/. /github/workspace/gh-pages -E -d /github/workspace/.doctree
  
  Running Sphinx v4.1.2
  Configuration error:
  config directory doesn't contain a conf.py file (/github/workspace/docs)
```

**Comment by jchodera** [comment]
Closing, since no longer relevant.
